export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const GET_USERS = "GET_USERS";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const CLEAR_USER = "CLEAR_USER";
export const USER_UPDATED = "USER_UPDATED";

export const CLEAR_FILTER = "CLEAR_FILTER";

export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const GET_CUSTOMER = "GET_CUSTOMER";
export const GET_CUSTOMERS = "GET_CUSTOMERS";
export const ADD_CUSTOMER = "ADD_CUSTOMER";
export const UPDATE_CUSTOMER = "UPDATE_CUSTOMER";
export const SET_CURRENT_CUSTOMER = "SET_CURRENT_CUSTOMER";
export const CLEAR_CUSTOMER = "CLEAR_CUSTOMER";
export const DELETE_CUSTOMER = "DELETE_CUSTOMER";
export const CUSTOMER_ERROR = "CUSTOMER_ERROR";
export const FILTER_CUSTOMER = "FILTER_CUSTOMER";

export const GET_SUPPLIER = "GET_SUPPLIER";
export const GET_SUPPLIERS = "GET_SUPPLIERS";
export const ADD_SUPPLIER = "ADD_SUPPLIER";
export const UPDATE_SUPPLIER = "UPDATE_SUPPLIER";
export const SET_CURRENT_SUPPLIER = "SET_CURRENT_SUPPLIER";
export const CLEAR_SUPPLIER = "CLEAR_SUPPLIER";
export const DELETE_SUPPLIER = "DELETE_SUPPLIER";
export const SUPPLIER_ERROR = "SUPPLIER_ERROR";
export const FILTER_SUPPLIER = "FILTER_SUPPLIER";

export const GET_ITEM = "GET_ITEM";
export const GET_ITEMS = "GET_ITEMS";
export const ADD_ITEM = "ADD_ITEM";
export const UPDATE_ITEM = "UPDATE_ITEM";
export const SET_CURRENT_ITEM = "SET_CURRENT_ITEM";
export const CLEAR_ITEM = "CLEAR_ITEM";
export const DELETE_ITEM = "DELETE_ITEM";
export const ITEM_ERROR = "ITEM_ERROR";
export const FILTER_ITEM = "FILTER_ITEM";

export const GET_ITEM_GROUP = "GET_ITEM_GROUP";
export const GET_ITEM_GROUPS = "GET_ITEM_GROUPS";
export const ADD_ITEM_GROUP = "ADD_ITEM_GROUP";
export const UPDATE_ITEM_GROUP = "UPDATE_ITEM_GROUP";
export const SET_CURRENT_ITEM_GROUP = "SET_CURRENT_ITEM_GROUP";
export const CLEAR_ITEM_GROUP = "CLEAR_ITEM_GROUP";
export const DELETE_ITEM_GROUP = "DELETE_ITEM_GROUP";
export const ITEM_GROUP_ERROR = "ITEM_GROUP_ERROR";
export const FILTER_ITEM_GROUP = "FILTER_ITEM_GROUP";

export const GET_WAREHOUSE = "GET_WAREHOUSE";
export const GET_WAREHOUSES = "GET_WAREHOUSES";
export const ADD_WAREHOUSE = "ADD_WAREHOUSE";
export const UPDATE_WAREHOUSE = "UPDATE_WAREHOUSE";
export const SET_CURRENT_WAREHOUSE = "SET_CURRENT_WAREHOUSE";
export const CLEAR_WAREHOUSE = "CLEAR_WAREHOUSE";
export const DELETE_WAREHOUSE = "DELETE_WAREHOUSE";
export const WAREHOUSE_ERROR = "WAREHOUSE_ERROR";
export const FILTER_WAREHOUSE = "FILTER_WAREHOUSE";

export const GET_UOM = "GET_UOM";
export const GET_UOMS = "GET_UOMS";
export const ADD_UOM = "ADD_UOM";
export const UPDATE_UOM = "UPDATE_UOM";
export const SET_CURRENT_UOM = "SET_CURRENT_UOM";
export const CLEAR_UOM = "CLEAR_UOM";
export const DELETE_UOM = "DELETE_UOM";
export const UOM_ERROR = "UOM_ERROR";
export const FILTER_UOM = "FILTER_UOM";

export const GET_CUSTOMER_GROUP = "GET_CUSTOMER_GROUP";
export const GET_CUSTOMER_GROUPS = "GET_CUSTOMER_GROUPS";
export const ADD_CUSTOMER_GROUP = "ADD_CUSTOMER_GROUP";
export const UPDATE_CUSTOMER_GROUP = "UPDATE_CUSTOMER_GROUP";
export const SET_CURRENT_CUSTOMER_GROUP = "SET_CURRENT_CUSTOMER_GROUP";
export const CLEAR_CUSTOMER_GROUP = "CLEAR_CUSTOMER_GROUP";
export const DELETE_CUSTOMER_GROUP = "DELETE_CUSTOMER_GROUP";
export const CUSTOMER_GROUP_ERROR = "CUSTOMER_GROUP_ERROR";
export const FILTER_CUSTOMER_GROUP = "FILTER_CUSTOMER_GROUP";

export const GET_SUPPLIER_GROUP = "GET_SUPPLIER_GROUP";
export const GET_SUPPLIER_GROUPS = "GET_SUPPLIER_GROUPS";
export const ADD_SUPPLIER_GROUP = "ADD_SUPPLIER_GROUP";
export const UPDATE_SUPPLIER_GROUP = "UPDATE_SUPPLIER_GROUP";
export const SET_CURRENT_SUPPLIER_GROUP = "SET_CURRENT_SUPPLIER_GROUP";
export const CLEAR_SUPPLIER_GROUP = "CLEAR_SUPPLIER_GROUP";
export const DELETE_SUPPLIER_GROUP = "DELETE_SUPPLIER_GROUP";
export const SUPPLIER_GROUP_ERROR = "SUPPLIER_GROUP_ERROR";
export const FILTER_SUPPLIER_GROUP = "FILTER_SUPPLIER_GROUP";

export const GET_INVENTORY = "GET_INVENTORY";
export const GET_INVENTORIES = "GET_INVENTORIES";
export const ADD_INVENTORY = "ADD_INVENTORY";
export const UPDATE_INVENTORY = "UPDATE_INVENTORY";
export const SET_CURRENT_INVENTORY = "SET_CURRENT_INVENTORY";
export const CLEAR_INVENTORY = "CLEAR_INVENTORY";
export const DELETE_INVENTORY = "DELETE_INVENTORY";
export const INVENTORY_ERROR = "INVENTORY_ERROR";
export const FILTER_INVENTORY = "FILTER_INVENTORY";
